# Generated by Django 3.0.6 on 2020-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_contact_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='image',
            new_name='image_file',
        ),
    ]
