# Generated by Django 3.0.6 on 2020-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200527_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
