# Generated by Django 3.0.6 on 2020-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200527_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image_file',
            field=models.ImageField(blank=True, help_text='(optional) profile pic', null=True, upload_to='images'),
        ),
    ]
