# Generated by Django 3.0.6 on 2020-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField(blank=True, null=True)),
                ('sendcc', models.BooleanField(default=False)),
                ('urgency', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('pricerange', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
